services:
  - type: web
    name: student-performance-predictor7
    runtime: python
    repo: https://github.com/Kumah-Caleb/Research-Project-V.1
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
