services:
  - type: web
    name: student-performance-predictor-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DB_SSL
        value: true
      - key: PGSSLMODE
        value: require
    plan: free
